FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    iputils-ping \
    curl \
    net-tools \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

RUN pip install fastapi uvicorn httpx

COPY main.py .

# Start the application directly
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]